server:
  port: 7777

spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
  jms:
    pub-sub-domain: true    # false = Queue,     true = Topic

# 自定义队列名称
mytopic: boot-activemq-topic
myqueue: boot-activemq-queue