server:
  port: 8888

spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
  jms:
    pub-sub-domain: false    # false = Queue,     true = Topic

# 自定义队列名称
myqueue: boot-activemq-queue
mytopic: boot-activemq-topic